name: personal-budget-app

services:
  backend:
    build:
      context: ./personal-budget-app-backend
      dockerfile: Dockerfile
    image: whlapinel/5166-final-project:backend
    ports:
      - "8080:8080"
    environment:
      PRODUCTION: "true"
    depends_on:
      - mariadb
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build:
      context: ./personal-budget-app-frontend
      dockerfile: Dockerfile
    image: whlapinel/5166-final-project:frontend
    ports:
      - "3000:3000"
    environment:
      - PRODUCTION=true
    networks:
      - appnet
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PORT: ${MARIADB_PORT}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3303:3306"
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:


volumes:
  mariadb-data:
